In [3]:
from IMPORTS import *

In [9]:
env = gym.make('CartPole-v0')
env.reset()
for _ in range(10):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()


In [ ]:
env = gym.make('MountainCar-v0')
env.reset()
for _ in range(10):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

In [12]:
m = Categorical(torch.tensor([ 0.25, 0.25, 0.25, 0.25 ]))
print(m.sample().item()) # equal probability of 0, 1, 2, 3

2


In [26]:
def discount_rewards(rewards, gamma=0.99):
    r = np.array([gamma**i * rewards[i] 
                  for i in range(len(rewards))])
    print('first - ',r)
    # Reverse the array direction for cumsum and then
    # revert back to the original order
    print('second - ',r[::-1])
    print('third - ',r[::-1].cumsum()[::-1])
    print('forth - ',r[::-1].cumsum()[::-1] - r[::-1].cumsum()[::-1].mean())
    r = r[::-1].cumsum()[::-1]
    return r - r.mean()

In [27]:
discount_rewards([1,1,1,1,1,1,1,1,1,1])

first -  [1.         0.99       0.9801     0.970299   0.96059601 0.95099005
 0.94148015 0.93206535 0.92274469 0.91351725]
second -  [0.91351725 0.92274469 0.93206535 0.94148015 0.95099005 0.96059601
 0.970299   0.9801     0.99       1.        ]
third -  [9.5617925  8.5617925  7.5717925  6.5916925  5.6213935  4.66079749
 3.70980744 2.76832729 1.83626194 0.91351725]
forth -  [ 4.38207501  3.38207501  2.39207501  1.41197501  0.44167601 -0.51892
 -1.46991005 -2.4113902  -3.34345555 -4.26620024]


array([ 4.38207501,  3.38207501,  2.39207501,  1.41197501,  0.44167601,
       -0.51892   , -1.46991005, -2.4113902 , -3.34345555, -4.26620024])

In [14]:
a = [1,1,1,1,1,1,1,1,1,1]


In [23]:
a = np.array(a)

In [25]:
a.cumsum()[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [30]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
logprob = np.array([(10,20),(10,20),(10,20),(10,20),(10,20),(10,20),(10,20),])

In [35]:
logprob[np.arange(7), [1,0,1,1,0,0,1]]

array([20, 10, 20, 20, 10, 10, 20])